# Generated by Django 5.0 on 2024-06-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PassPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys', models.TextField(max_length=500, unique=True)),
                ('amount_of_pi', models.CharField(blank=True, max_length=100, null=True)),
                ('unlock_date', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('look_up', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Keys',
                'verbose_name_plural': 'Keys',
                'ordering': ['-date'],
            },
        ),
    ]
